### ISSUE TITLE
Remove blip

### ISSUE THREAD

**Issue by OfficialRDB** [qbcore-framework/qb-jewelery#11]
I'm trying to remove the blip for the players eyes but it doesn't remove with: **RemoveBlip(blip)** It worked for other scripts.

**Comment by SovietRulez** [comment]
@OfficialRDB Do you mean the blip on the map?

**Comment by SovietRulez** [comment]
https://sovietrulez.file.glass/6dcf2
This?

**Comment by OfficialRDB** [comment]
> 
> 
> https://sovietrulez.file.glass/6dcf2
> This?

Yes, and normal around line 280 you can add the remove blip, but that doesn't work for me.

**Comment by jnccloud** [comment]
That's the blip for police when it is being robbed. You want to remove the map blip, which is at the bottom of the file:

```lua
Citizen.CreateThread(function()
    Dealer = AddBlipForCoord(Config.JewelleryLocation["coords"]["x"], Config.JewelleryLocation["coords"]["y"], Config.JewelleryLocation["coords"]["z"])

    SetBlipSprite (Dealer, 617)
    SetBlipDisplay(Dealer, 4)
    SetBlipScale  (Dealer, 0.7)
    SetBlipAsShortRange(Dealer, true)
    SetBlipColour(Dealer, 3)

    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName("Vangelico Jewelry")
    EndTextCommandSetBlipName(Dealer)
end)
```

Just delete that entire thread
