### ISSUE TITLE
Cop count set to 6 but still ppl can rob jewelry without any cops online

### ISSUE THREAD

**Issue by SKITTLE6969** [qbcore-framework/qb-jewelery#24]
cop count not working for some reason 

![image](https://user-images.githubusercontent.com/92496158/161427174-89a656a9-b217-4182-bfb2-76d4787f8352.png)
![image](https://user-images.githubusercontent.com/92496158/161427194-8cb12507-5155-46db-adaf-d72f65f8d2b3.png)

**Comment by milotiro95** [comment]
Same problem for me !

**Comment by milotiro95** [comment]
I downgrade then my version until it's fixed ...

**Comment by SKITTLE6969** [comment]
> I downgrade then my version until it's fixed ...

this happens only when target is true when its set to false works perfectly fine

**Comment by milotiro95** [comment]
I means this update is for qb-target is disable what the point of upgrade the version for except locales ? If it's only on the qb-target enable it should be an error into the config.target somewhere else next to the police alerts.
