### ISSUE TITLE
Smasing vitrine

### ISSUE THREAD

**Issue by MrRasmus** [qbcore-framework/qb-jewelery#31]
Vitrines dosent show as smashed when doing the jewelery robbery?

**Comment by tom-osborne** [comment]
> Vitrines dosent show as smashed when doing the jewelery robbery?

Hi @MrRasmus please can you elaborate on your issue? I don't understand

**Comment by tvasa** [comment]
I think je means the vlasy on vitrine doesnt crack And still undamaged after rob thé vitrine. @tom-osborne

**Comment by MriKNG** [comment]
Reinstall the script by downloading the latest version from here. You should be good to go.
