### ISSUE TITLE
[BUG] Error when used with qb-target

### ISSUE THREAD

**Issue by XLightDev** [qbcore-framework/qb-jewelery#37]
#I'm sorry if you don't understand I am not good at English

setr UseTarget false I haven't encountered a problem.

But when setr UseTarget true ,  when the player join to the server later it can repeatedly smash the glass cabinet multiple no limit

setr UseTarget true - no notification if u dont have a weapon on ur hand prior to activating the robbery

*** how to BUG
how to BUG  initiate the theft, logout and rejoin the server. After that, before you hold the weapon You smash the mirrors a few times before holding a weapon and smash unlimited mirrors over and over.

**Comment by XLightDev** [comment]
video how to bug https://cdn.discordapp.com/attachments/959876640941441044/992427895236599869/2022-07-01_20-48-36.mp4

**Comment by tom-osborne** [comment]
@XLightDev thanks for raising this. Is the logging out /rejoining server important to the bug? (Does the bug still happen if you dont log out?)

**Comment by XLightDev** [comment]
You did not log out, no errors.

but there is only one thing There is no notification for you to weapon in hand.

But for players who enter the server after the theft starts. Will be able to break glass cabinet repeatedly without limit.
Players who log in to the server later can smash the original glass cabinet that has already been stolen.

**Comment by XLightDev** [comment]
It's a major mistake. I hope this is fixed :)

**Comment by tom-osborne** [comment]
> It's a major mistake. I hope this is fixed :)

@XLightDev following the steps in the video, I cannot replicate the issue. Are you certain you are using the latest version of the script?

**Comment by XLightDev** [comment]
> > It's a major mistake. I hope this is fixed :)
> 
> @XLightDev following the steps in the video, I cannot replicate the issue. Are you certain you are using the latest version of the script?

latest version of script

**Comment by XLightDev** [comment]
Why I can latest

https://cdn.discordapp.com/attachments/997679594956128256/1000541408018575360/2022-07-24_06-08-38.mp4

**Comment by XLightDev** [comment]
If you restart the resource, it won't be able to do this bug.
This can be done when entering the game for the first time, and qb-target enabled.

**Comment by XLightDev** [comment]
I turned off that function. It appears that it cannot do such a defect. But the players who enter the server later will not be synced

![image](https://user-images.githubusercontent.com/108535266/180629627-f17d019e-06d8-41a2-94c9-fbf541af81a6.png)

**Comment by XLightDev** [comment]
@tom-osborne I solved the problem. Bug caused by activating qb-target like Video.
![image](https://user-images.githubusercontent.com/108535266/180631103-14120a56-6fbc-47f1-a43e-37e95ca23520.png)

**Comment by tom-osborne** [comment]
> @tom-osborne I solved the problem. Bug caused by activating qb-target like Video. [image]

Interesting, looks like your code is doing the exact same thing, only using the index. Have you changed anything in your config for this script? If so, can you share it?

**Comment by SKITTLE6969** [comment]
I also had this issue the above fixed it smh

**Comment by OpheliaRedRose** [comment]
Light's fix works for me as well.
