### ISSUE TITLE
[BUG] Rewards only rewarding `tenkgoldchain`

### ISSUE THREAD

**Issue by Chiefink5** [qbcore-framework/qb-jewelery#66]
**Describe the bug**
The script is calling for a single specific item to be rewarded if the `otherchance` is not odd. Due to this, regardless of configuration and the items added/removed to the VitrineRewards, the only possible reward when robbing the jewelry store is the tenkgoldchain. *(i have completely removed the default 3 rewards, yet im still only rewarded the tenkgoldchain)*
![image](https://github.com/qbcore-framework/qb-jewelery/assets/117122333/6e440309-0cc2-41a4-981c-b71387042342)

1. Go to 'qb-jewelery/server/main.lua' and examine lines 80-94 to find the code calling for the `tenkgoldchain` to be awarded if `otherchance = odd` *(listed above and below)*
2. Go in-game and attempt to rob the jewelry store
3. See error

**Expected behavior**
You're supposed to be able to get rewarded any of the configured items under the VitrineRewards Config section when robbing the jewelry store.

**Screenshots**
![image](https://github.com/qbcore-framework/qb-jewelery/assets/117122333/3d248cb4-c513-415c-95c8-8b81267e291f)
![image](https://github.com/qbcore-framework/qb-jewelery/assets/117122333/2b3edebb-e7fe-48db-890d-3c9e63b1ecd8)
![image](https://github.com/qbcore-framework/qb-jewelery/assets/117122333/f7e98669-8b3b-4790-bef1-83fed4211380)

**Questions (please complete the following information):**
 - When you last updated: `Today, as i thought that could be the reasoning behind the unsucessful robbery attempts`
 - Are you using custom resource? `'qb-target'`
 - Have you renamed `qb-` to something custom? `No.`

**Additional context**
N/A for now.

**Comment by LoadedGuns** [comment]
I cant even get that far, when we rob it, our inventorys wont even open anymore

**Comment by SinisterDevelopment** [comment]
looking into this issue right now! if i can make it happen i will fix and issue the PR

**Comment by Chiefink5** [comment]
Awesome, I appreciate it!
